language: node_js
os:
  - linux
node_js:
  - "12.14.1"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  - provider: pages
    token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: build
    target_branch: master
    on:
      branch: production
